name: Deploy Terraform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "subscription_id=$ARM_SUBSCRIPTION_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "subscription_id=$ARM_SUBSCRIPTION_ID"
